### ISSUE TITLE
multiple crates in the same workspace cannot reuse the same cache

### ISSUE THREAD

**Issue by fzyzcjy** [mityax/rustimport#11]
Hi thanks for the helpful library! However, seems that multiple crates in the same workspace should cannot the same cache. For example, I have crate A and crate B both inside workspace W. Then, I use rustimport and import both A and B in my python code. Then, seems that the two are compiled separately, thus it both takes twice the CPU and twice the disk. It would be great if A and B can reuse the same cache, just like what it is done in standard rust cargo workspaces.

**Comment by mityax** [comment]
Hi, what's your usecase? Do you have several crates to be imported with rustimport within one workspace?

Ehen implementing workspace support I though about this problem,

**Comment by fzyzcjy** [comment]
> but I came to the conclusion that usually you'd have one create imported by Python and the other ones in the workspace would be pure-rust.

Hmm good idea, I may refactor code into this

**Comment by mityax** [comment]
Fixed now in [70f172b](https://github.com/mityax/rustimport/commit/70f172b1ccce695ae929b314fa8c95cd701b07d7)
