### ISSUE TITLE
Warning message crashes release build

### ISSUE THREAD

**Issue by davystrong** [mityax/rustimport#13]
Running `python -m rustimport build --release`, crashes if it detects a potential importable crate because the warning (`notify_potential_failure_reason`) attempts to split `None`. This happens because, unlike when importing a package, the `fullname` argument is left undefined. I could submit a PR but I'm not sure what the best approach is. Should I only show the message if `fullname` is defined or should I show a different, more generic message? Since `python -m rustimport build --release` searches for all possible matches, showing any warning risks producing a lot of unnecessary warnings, so I would probably just leave out potential matches.

This happens in the `try_create` method of `CrateImportable`, and presumably would also happen in the `try_create` method of `SingleFileImportable`.

**Comment by mityax** [comment]
Thanks for reporting – I  fixed it [this way](68255aca4d1edec4f0c321dbe733cb951c13b352) now – failure reason are now only reported if a `fullname` is given – i.e. if a module is tried to be imported, not when being built using the cli.

**Comment by davystrong** [comment]
Great, that's working now! Thanks!
