### ISSUE TITLE
Enhancement: Jupyter support

### ISSUE THREAD

**Issue by itamarst** [mityax/rustimport#22]
It should be possible to use `rustimport` to create a Jupyter integration that would allow having cells written in Rust.

* A Jupyter magic; the Cython one is a relevant example (https://github.com/cython/cython/blob/master/Cython/__init__.py).
* Some way to mark a cell as being in Rust, i.e. syntax highlighting. https://github.com/jupyterlab/jupyterlab/issues/2143 has some links to prior art.

The actual logic when executing a cell would be:

1. Write to a random file.
2. Compile the extension.
3. Import the extension.
4. Do the the equivalent of `from new_random_named_extension import *` so all the newly defined functions and classes are loaded into the same namespace as the rest of the Jupyter code.

**Comment by mityax** [comment]
That'd be a handy feature for sure. I probably won't be able to develop this myself in the near future due to time constraints, but I'm open to any contribution regarding this.
