### ISSUE TITLE
How can i use this with structs? 

### ISSUE THREAD

**Issue by ashercn97** [mityax/rustimport#25]
How can I use rustimport with structs?

**Comment by mityax** [comment]
Just add them to your file as you'd do with PyO3 normally:

```rust
// rustimport:pyo3

use pyo3::prelude::*;

#[pyclass]
struct Integer {
    inner: i32,
}

#[pyfunction]
fn square(x: i32) -> i32 {
    x * x
}
```

**Comment by ashercn97** [comment]
Oh okay tysm!

**Comment by ashercn97** [comment]
Two more questions: (sorry ive never used pyo3 before) do i need to do the methods and how do i do the pymodule thing at the end?

**Comment by mityax** [comment]
1. No, you don't need to define any methods technically. However, I wouldn't know why you'd use rust in your projects if you don't define any methods since it's speed benefit is useless then. Maybe I didn't understand your question correcrly though (?)
2. You can entirely omit the pymodule part, see the rustimport readme for more on that, or refer to the `examples` folder in this repo.

**Comment by ashercn97** [comment]
@mityax  I meant do i have to like wrap the methods in the #[whatever] ?

**Comment by ashercn97** [comment]
@mityax  I have my rust file in a src folder and then i defined the Cargo.toml like this:


[package]
name = "frac"
version = "0.1.0"
edition = "2021"

[lib]
name = "frac"
path = "src/frac.rs"
crate-type = [ "cdylib",]

[dependencies.pyo3]
version = "0.16.2"
features = [ "extension-module",]

and then from outside the source im trying to import frac and it keeps telling me it isnt a thing? Do you know why?

**Comment by ashercn97** [comment]
like what wrapper thing do i do for methods?

**Comment by mityax** [comment]
Methods need to be annotated by `#[pyfunction]`

I don't know what's wrong in your setup as I don't know enough about it. Your simplest option is probably to let the tool generate a crate for you and then import it:

```bash
python3 -m rustimport new my_crate
```

This will create a folder `./my_crate` with a `Cargo.toml` and `src` subfolder. You can then just import that crate from `./main.py` or whatever your script is called

**Comment by ashercn97** [comment]
okay ty
