### ISSUE TITLE
latest pyo3 compatability

### ISSUE THREAD

**Issue by jermatic** [mityax/rustimport#30]
warning: use of deprecated method `pyo3::deprecations::GilRefs::<T>::function_arg`: use `&Bound<'_, T>` instead for this function argument
  --> polars_ext/src/lib.rs:28:28
   |
28 | fn polars_ext(_py: Python, m: &PyModule) -> PyResult<()> {
   |                            ^
   |
   = note: `#[warn(deprecated)]` on by default

**Comment by mityax** [comment]
Thanks for reporting – should be fixed by 4a79fc6.

Please update to the latest `rustimport` release using pip
