### ISSUE TITLE
ModuleNotFound when running single python module from VSCode 

### ISSUE THREAD

**Issue by mmlynarik** [mityax/rustimport#32]
Hi, 

just wanted to ask what is right procedure to allow the compiled rust extension module to be importable in python files that are run as standalone scripts or that are part of e.g. Django application. In your readme file, you are only demonstrating launching the rust function from python interpreter window. How should we replicate the functionality also for standalone scripts and apps? Currently, I'm always getting the `ModuleNotFoundError` even though I first `import rustimport.import_hook`. On the other hand, if I open the python interpreter and run the code, it works. I would be really thankful if this worked also outside python interpreter.

![obrázok](https://github.com/user-attachments/assets/a802031a-022b-4faf-8e20-587b347fa6b2)

Thanks!

Miro

**Comment by mmlynarik** [comment]
I managed to work arount it, by building the extension from python interpreter and copying the `.so` file into right folder. But the question is, how should be the python file informed where to look for the rust extension? Is there a way how the `.so` file does not need to be located in the folder where the file importing it is located?

**Comment by mmlynarik** [comment]
Found the solution.

**Comment by mityax** [comment]
Glad you found the solution :)
