### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by fzyzcjy** [mityax/rustimport#4]
Hi thanks for the crate - I wonder whether it is ready for production or is still under development or alpha?

**Comment by mityax** [comment]
Hm, I'd say rustimport is as production ready, as a small project like this can be. That is:

 - It's codebase is fairly clean, there is no major refactoring necessary and serious bugs are very unlikely
 - I do test all of the `examples` before releasing a new version (there are no unit tests yet though)
 - However, it has (at least to my knowledge) not really been battle-tested, given a popularity of about 50-60 pypi downloads per month and
 - though I'm motivated to fix bugs quickly I can't offer anything like professional support or guarantees for this project.

So, there's no major breaking changes or anything planned, code-quality wise, it should be pretty reliable and if you follow the [Usage in production](https://github.com/mityax/rustimport#usage-in-production) instructions, it should work fine for you.

However, if you prefer to go the safest and a bit more complex way, a tool like `maturin` might be better suited for you.

**Comment by fzyzcjy** [comment]
Thanks, I have tried it and it works great (except for some bugs) :)

**Comment by mityax** [comment]
Could you kindly tell me what bugs you found, so I might fix them? Thx

**Comment by fzyzcjy** [comment]
#6 indeed - and you have fixed it quickly! :)
