### ISSUE TITLE
Rustimport does not understand relative imports or workspaces

### ISSUE THREAD

**Issue by fzyzcjy** [mityax/rustimport#6]
Hi thanks for the lib! But it does not work for me:

I have a cargo workspace with two crates, A and B. A depends on B. Then when python wants to import A, it cannot compile, because the rustimport-managed codes for A does not recognize B.

**Comment by mityax** [comment]
Hi, support for cargo workspaces was not implemented before. I did implement a patch for it now though, and a new version has been released – I'm curios for your feedback.

Note: There is a working example workspace in the examples folder, in case there are any uncertainties on how to set the structure up.

**Comment by fzyzcjy** [comment]
Wow thanks for the new feature! I will try it soon and provide some feedbacks

**Comment by fzyzcjy** [comment]
It works 🎉
